### ISSUE TITLE
Sweep: Update the API webpage with new functions and classes

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [time-series-machine-learning/tsml-eval#110]
### Details

The Sphinx API webpage at `docs/api.md` is missing links to pages for multiple public functions and classes throughout the `tsml_eval/` package, for example those in `tsml_eval/experiments/forecasting_experiments.py`. This markdown webpage is parsed using MyST.

Add any missing public functions and classes in `tsml_eval/` to the API webpage in line with the current format used in `docs/api.md`. 

Put each function or class in a section with other functions from the same top-level module.

Do not add classes and functions from `tsml_eval/estimators` to the API in this pull request.

### Files to change

```Shell
docs/api.md
```

<details open>
<summary>Checklist</summary>

- [X] `docs/api.md` ✅ Commit [`3fb0ba0`](https://github.com/time-series-machine-learning/tsml-eval/commit/3fb0ba0261c6fe60e8eef1c9eeb955d7b23f5179)
</details>

**Comment by MatthewMiddlehurst** [comment]
sweep: retry

**Comment by MatthewMiddlehurst** [comment]
sweep: retry

**Comment by MatthewMiddlehurst** [comment]
sweep: retry

**Comment by kevinlu1248** [comment]
Sweep: retry

**Comment by MatthewMiddlehurst** [comment]
sweep: retry

**Comment by kevinlu1248** [comment]
sweep: retry

**Comment by kevinlu1248** [comment]
Hey sorry this ticket hasn't been working out, we've just been working a lot on patching reliability issues of Sweep due to a recent migration so haven't gotten the chance to give this a thorough investigation yet. We're gonna set up a better way to monitor sessions soon that will make debugging this a lot easier. I'll also fork this and run this through a locally running instance of Sweep to test it out. My hunch is that this has something to do with certain files being hard to chunk or embed which freezes the process.

**Comment by MatthewMiddlehurst** [comment]
My PR here seems to be having issues also https://github.com/aeon-toolkit/aeon/pull/737, it created fine but wont update with my comment.

Shot in the dark, but the docs folder in both repos contains symbolic links to other parts (examples in both, a publications package here), could that be causing an issue? Don't know how common that is.

**Comment by kevinlu1248** [comment]
@MatthewMiddlehurst We were having issues this morning with comments, but it's fixed now so I gave it another shot. And yes symlinks do cause problems for now but usually, it would fail instead of freezing so this is strange.

**Comment by MatthewMiddlehurst** [comment]
sweep: retry

**Comment by MatthewMiddlehurst** [comment]
sweep: retry
