### ISSUE TITLE
tsml_eval.experiments.classification_cross_validation not available in tsml_eval 0.3.0

### ISSUE THREAD

**Issue by lngdet** [time-series-machine-learning/tsml-eval#233]
### Describe the issue

In the documentation, [tsml_eval.experiments.classification_cross_validation](https://tsml-eval.readthedocs.io/en/latest/auto_generated/tsml_eval.experiments.classification_cross_validation.html#tsml_eval.experiments.classification_cross_validation) is referenced. But when I do:

`from tsml_eval.experiments import classification_cross_validation`

I get an error saying it doesn't exist:

> ImportError: cannot import name 'classification_cross_validation' from 'tsml_eval.experiments'

I'm using version 0.3.0

**Comment by MatthewMiddlehurst** [comment]
Hi, the documentation was pointing to the `main` branch instead of the latest release by default. I have changed it to point to the release so lessen confusion.

You can use these functions by installing the latest github build rather than the pypi release, or wait until we make a new pypi release.

**Comment by lngdet** [comment]
thank you for the info
