### ISSUE TITLE
[Bug] Missing file for clustering and regression scripts in soton HPC

### ISSUE THREAD

**Issue by IRKnyazev** [time-series-machine-learning/tsml-eval#282]
### Describe the bug

The clustering_experiments.sh and regression_experiments.sh (found in "/tsml-eval/_tsml_research_resources/soton/iridis/classification_experiments.sh") refer to accessing DataSetLists from Tony's directory inside Lyceum. His DataSetLists directory (/mainfs/home/ajb2u23/DataSetLists/) currently only contains a list for classification experiments. 

### Expected results

The clustering_experiments.sh and regression_experiments.sh should be provided a correct filepath for the corresponding DataSetLists.

### Actual results

Either an incorrect file path is given, or the relevant dataset lists do not currently exist.

**Comment by MatthewMiddlehurst** [comment]
These are just example values, its not expected for anyone to use them, The intended usage for these is for people to go through the script and set their own values. 

It would be better to go through the script and make sure they are invalid so it causes a crash IMO.
