### ISSUE TITLE
Discrepancy in average accuracy between original InceptionTime repository and this repository

### ISSUE THREAD

**Issue by xumwen** [time-series-machine-learning/tsml-eval#68]
I have recently been working on a project that references the InceptionTime original repository, and during my analysis, I noticed an inconsistency between the metric results in our repository and the original repository. 

By comparing the average accuracy between the two repositories, using the same datasets and test parameters, I've found that InceptionTime's original repository has an average accuracy of 0.836 for 128 datasets in UCR over five runs, and tsml repository has an average accuracy of 0.871 for 108 datasets in UCR.

I have attached the links for the results for reference. 
Original results of InceptionTime: https://github.com/hfawaz/InceptionTime/blob/master/results-inception-128.csv
TSC results: https://www.timeseriesclassification.com/results/tsml/tsmlUnivariateResults.zip (I guess the test results with the original train/test split can be found in .\tsmlUnivariateResults\MegaComparison\ACC\TEST\TESTACC_MEANS)

I would greatly appreciate any help and clarification in understanding if my comparison and results are incorrect or if there is a reason for this inconsistency. 

Thank you for your assistance.

**Comment by xumwen** [comment]
I believe that the "TESTACC_MEANS" represents the average accuracy of 30 resamples.
The result for the original split can be found in resample 0.
I would like to confirm if my understanding is correct.

Thank you for your help!

**Comment by xumwen** [comment]
That's the point. I just noticed that InceptionTime used an ensemble of 5 individual networks by default.
Thank you for your reply!

**Comment by MatthewMiddlehurst** [comment]
Closing this, feel free to open if there is still an issue or you have any more questions.
