### ISSUE TITLE
different result in the "The great multivariate time series classification bake off" and the CSV result in www.timeseriesclassification.com

### ISSUE THREAD

**Issue by YunruiZhang** [time-series-machine-learning/tsml-eval#86]
Hi,

I found that the results in the "The great multivariate time series classification bake off" paper and the result csv table downloaded from http://www.timeseriesclassification.com/results/AllAccuracies.zip are totally different. 

For instance, in the file MultivariateAveragedOver30Resamples.csv the result for ROCKET seems to be the result for STC in the bake-off paper. This is not only the case the other results all seems to be in different positions. 

I wonder which version of the result shall I trust.

Best regards,
Yunrui Zhang

**Comment by YunruiZhang** [comment]
The CSVs are obtained from https://www.timeseriesclassification.com/results/tsml/tsmlMultivariateResults.zip

**Comment by TonyBagnall** [comment]
hmm, I'll tsake a look, thanks.

**Comment by YunruiZhang** [comment]
Hi, is there any update on this issue? I saw the link I mentioned above been taken down but the results in this repo are still incorrect compared to the result in the multivariant bake-off appendix.  I am trying to use these results in my comparison. Shall I just use the result from the multivariant bake-off paper?

Thanks a lot.
Yunrui

**Comment by MatthewMiddlehurst** [comment]
I would trust the results in the paper if you can use those. Not sure what went wrong with the upload sorry!

**Comment by YunruiZhang** [comment]
Thank you for your reply!

**Comment by TonyBagnall** [comment]
sorry for the delay, going to try sort this and results generally out over the next  couple of weeks

**Comment by YunruiZhang** [comment]
No worries, in the end, I use the HC2 results from http://www.timeseriesclassification.com/results/HC2/
MTSC-SOTA-AverageOver30.csv which does not seem to have any issue.

**Comment by YunruiZhang** [comment]
Hi, the results are still not available on https://www.timeseriesclassification.com/results/tsml/. Are the results in [https://github.com/time-series-machine-learning/tsml-eval/tree/main/results](url) correct?

Thanks

**Comment by MatthewMiddlehurst** [comment]
I believe they are a mix of the bake off paper and HC2. The download links on the webpage don't seem to be working for me either @TonyBagnall.

**Comment by MatthewMiddlehurst** [comment]
Closing this for now. Post again if there are still issues.
